[package]
name = "rmf_sandbox"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "librmf_sandbox"

[[bin]]
path = "src/main.rs"
name = "rmf_sandbox"

[dependencies]
bevy = "0.7"
bevy_egui = "0.13"
rfd = "0.8.2"
serde_yaml = "0.8.23"
wasm-bindgen = "0.2"
web-sys = { version = "0.3.56", features = ["console"] }
yaml-rust = "0.4"
futures-lite = "1.12.0"


# Need to handle WASM case seperately
#[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
#futures = "0.3"

#[target.'cfg(target_arch = "wasm32")'.dependencies]
#wasm-bindgen-futures = "0.4.30"
