name: style

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  style:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: rustfmt
      run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu

    - name: style
      run: cd rmf_sandbox && rustfmt --check --edition 2021 src/*
